#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 18 03:09:45 2025

@author: felipemoret
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Global configuration file for the Market Making + LOB simulation environment.

This file provides:
    - a global random seed (full reproducibility)
    - all simulation parameters (lam, mu, delta, arrival times)
    - additional placeholders for future constants
    - clean seeding for Python, NumPy, and PyTorch

Import this module in any script to ensure consistent configuration.
"""

import numpy as np
import random
import torch

# ============================================================
# 1) GLOBAL SEED FOR FULL REPRODUCIBILITY
# ============================================================

GLOBAL_SEED = 123

def seed_all(seed: int = GLOBAL_SEED) -> None:
    """Seed all RNGs for reproducibility. Call explicitly rather than at import."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

# Seed once at import for backward compatibility.
# Callers should call seed_all(seed) explicitly before each run.
seed_all(GLOBAL_SEED)


# ============================================================
# 2) LOB SIMULATION PARAMETERS
# ============================================================

"""
lam  : intensity of limit-order arrivals
mu   : intensity of market-order arrivals
delta: intensity of cancellations / order evaporation
"""

#Based on AMZN Santa Fe Calibration
lam = 0.06
mu = 0.1
delta = 0.02


# ============================================================
# 3) LOB ENGINE SELECTION: Santa Fe vs QRM
# ============================================================
#
# USE_QRM = False  →  Santa Fe constant-rate engine (default)
# USE_QRM = True   →  Queue-Reactive Model (loads qrm_calibration.pkl)
#
# The .pkl file is generated by parameters_estimation_QRM.ipynb.
# When using QRM, (lam, mu, delta) above are still required in the
# function signature but are IGNORED — intensities come from the
# calibrated tables inside qrm_params.

USE_QRM = False

if USE_QRM:
    import pickle, os
    _pkl_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "qrm_calibration.pkl")
    if not os.path.isfile(_pkl_path):
        raise FileNotFoundError(
            f"USE_QRM=True but calibration file not found: {_pkl_path}\n"
            "Run parameters_estimation_QRM.ipynb first to generate it."
        )
    with open(_pkl_path, "rb") as _f:
        _calib = pickle.load(_f)

    # Extract calibrated order sizes (used by simulate_LOB_with_MM)
    mean_size_LO = _calib.get("mean_size_LO", 1)
    mean_size_MO = _calib.get("mean_size_MO", 1)

    # Build qrm_params dict passed to _create_lob_engine()
    qrm_params = dict(
        intens_val       = _calib.get("intens_val"),
        intens_k1        = _calib.get("intens_k1"),
        intens_val_bis   = _calib.get("intens_val_bis"),
        statprob         = _calib.get("statprob"),
        intens_levels    = _calib.get("intens_levels"),
        size_q           = _calib.get("size_q"),
        size_s           = _calib.get("size_s", 2),
        aes              = _calib.get("aes", 1.0),
        intensity_model  = _calib.get("intensity_model", _calib.get("base_model", "I")),
        # Defensive: check explicitly for None so that calibrated 0.0
        # or False values are preserved (not overwritten by defaults).
        use_dynamic_pref = _calib["use_dynamic_pref"] if _calib.get("use_dynamic_pref") is not None else True,
        theta            = _calib["theta"] if _calib.get("theta") is not None else 0.05,
        theta_reinit     = _calib["theta_reinit"] if _calib.get("theta_reinit") is not None else 0.10,
        tick_qrm         = _calib.get("tick_qrm", 0.01),
        # Model IIA/IIB specific (None if not calibrated)
        intens_k2_q1pos      = _calib.get("intens_k2_q1pos"),
        intens_k2_q1zero     = _calib.get("intens_k2_q1zero"),
        intens_k1_by_regime  = _calib.get("intens_k1_by_regime"),
        iib_m                = _calib.get("iib_m"),
        iib_l                = _calib.get("iib_l"),
        midlimit_rate        = _calib.get("midlimit_rate", 0.0),
        reinit_k2_data       = _calib.get("reinit_k2_data"),
        aes_by_level         = _calib.get("aes_by_level"),
        iib_joint_invariant  = _calib.get("iib_joint_invariant"),
        model_k1_invariant   = _calib.get("model_k1_invariant"),
        size_q_by_level      = _calib.get("size_q_by_level"),
    )
    del _calib, _f, _pkl_path
else:
    qrm_params = None
    mean_size_LO = 1
    mean_size_MO = 1


# ============================================================
# 4) OPTIONAL: PLACEHOLDERS FOR FUTURE CONSTANTS
# ============================================================

# Example placeholders (commented out):
# MAX_INVENTORY = 50
# DEFAULT_TICK_SIZE = 1
# SIMULATION_LENGTH = 10000
# REWARD_INVENTORY_COEFF = 0.1


# ============================================================
# 4) PRINT CONFIG (optional)
# ============================================================

if __name__ == "__main__":
    print("=== CONFIG_MM.py loaded successfully ===")
    print(f"GLOBAL_SEED: {GLOBAL_SEED}")
    print(f"lam: {lam}")
    print(f"mu: {mu}")
    print(f"delta: {delta}")
