"""
Generic RL controller interface for the MarketMaker + LOB simulator.

This file defines a Protocol that any RL algorithm must implement.
Examples:
    - SARSA / Expected-SARSA (tabular)
    - DQN
    - PPO
    - Custom RL methods or heuristics

The simulator only depends on this interface. It does NOT import any
specific RL implementation.

IMPORTANT:
    - To avoid circular imports, this module does NOT import MarketMaker
      or LOB_simulation at runtime.
    - For type checking only, we use TYPE_CHECKING and forward references.
"""

from typing import Any, Dict, Protocol, TYPE_CHECKING

# These imports are only for static type checkers.
# They are NOT executed at runtime → prevents circular imports.
if TYPE_CHECKING:
    from MM_LOB_SIM import MarketMaker
    from LOB_SIM import LOB_simulation


class RLController(Protocol):
    """
    Interface for any reinforcement learning controller interacting with:

        - MarketMaker (action generation + execution)
        - LOB_simulation engine (environment dynamics)
        - State transitions (state_before → state_after)
        - Reward function provided by the user

    A valid RL controller must implement:

        act(mm_state) -> action_tuple
        learn(step_idx, mm, lob, state_before, state_after, reward, info)

    The runner will call:

        action = controller.act(state_before)
        ...
        controller.learn(...)

    The runner never accesses internal RL logic:
        - No direct access to Q-table
        - No direct access to networks
        - No dependency on algorithm type
    """

    # -------------------------------------------------------------
    # ACTION SELECTION INTERFACE
    # -------------------------------------------------------------
    def act(self, mm_state: Dict[str, Any]) -> tuple:
        """
        Select an action based on the current MarketMaker state.

        Parameters
        ----------
        mm_state : dict
            State dictionary generated by MarketMaker.build_state().
            Contains fields such as:
                "mid", "best_bid", "best_ask",
                "spread", "bidsize", "asksize",
                "obi", "inventory",
                and possibly more depending on MM design.

        Returns
        -------
        action : tuple
            Action tuple understood by MarketMaker.pre_step(), e.g.:

                ("place_bid", price)
                ("place_ask", price)
                ("place_bid_ask", bid_price, ask_price)
                ("cancel_all",)
                ("hold",)
        """
        ...

    # -------------------------------------------------------------
    # LEARNING INTERFACE
    # -------------------------------------------------------------
    def learn(
        self,
        step_idx: int,
        mm: "MarketMaker",               # forward reference (type checker only)
        lob: "LOB_simulation",           # forward reference (type checker only)
        state_before: Dict[str, Any],
        state_after: Dict[str, Any],
        reward: float,
        info: Dict[str, Any],
    ) -> None:
        """
        Apply one update step of the RL algorithm.

        Called AFTER:
            - the MarketMaker action is executed
            - the environment event is processed (arrival, cancel, etc.)
            - state_after is computed
            - reward_fn has produced a scalar reward

        Parameters
        ----------
        step_idx : int
            Current step index inside the episode.
        mm : MarketMaker
            MarketMaker instance controlling inventory, orders, etc.
        lob : LOB_simulation
            Underlying limit-order-book engine.
        state_before : dict
            State dictionary before the environment event.
        state_after : dict
            State dictionary after the environment event.
        reward : float
            Scalar reward produced by the reward function.
        info : dict
            Additional metadata for debugging or learning:
                - order_type
                - fills detected this step
                - last_fill info
                - queue position signals
                - etc.

        Returns
        -------
        None
        """
        ...
